repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-genome_annotator_logo_light.png
    - docs/images/nf-core-genome_annotator_logo_light.png
    - docs/images/nf-core-genome_annotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - .github/.dockstore.yml
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-genome_annotator_logo_light.png
    - docs/images/nf-core-genome_annotator_logo_light.png
    - docs/images/nf-core-genome_annotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - .github/.dockstore.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
  readme:
    - nextflow_badge
  included_configs: false

template:
  org: EGCE
  name: genome_annotator
  description: Pipeline dedicated to genome annotation
  author: Olivier Coen
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - github
    - igenomes
    - fastqc
    - nf_core_configs
    - seqera_platform
    - gpu
    - codespaces
    - vscode
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
